# Generated by Django 6.0 on 2025-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default='Default Semester', help_text="Label e.g. '1st Semester'", max_length=50),
            preserve_default=False,
        ),
    ]
